### ISSUE TITLE
Python lib directory question

### ISSUE THREAD

**Issue by DBraun** [vadimkantorov/wigwam#5]
I encountered an issue while using wigwam to install opencv. Wigwam looks for python in .wigwam/prefix/python/lib, but this python doesn't exist. It does exist in /usr/lib/python2.7. How can I successfully install opencv?

My ~/.bashrc has alias wigwam='python2.7 <($([ -z "$(which curl)" ] && echo "wget -nv -O -" || echo "curl -sS") https://raw.githubusercontent.com/vadimkantorov/wigwam/master/wigwam.py) --repo https://github.com/vadimkantorov/wigwam/tree/master/wigs'

OS: Ubuntu 16.04 LTS 64-bit

machine@computer:~/Downloads/mpegflow-master$ wigwam init && wigwam install opencv ffmpeg
10 packages to be installed in the order below:
    cython
     bzip2
     cmake
      zlib
      yasm
    ffmpeg    requires  bzip2, lzma, zlib, yasm
pkg-config
  openblas
     numpy    requires  cython, openblas
    opencv    requires  cmake, pkg-config, ffmpeg, numpy

Updating installation script...  ok [/home/machine/Downloads/mpegflow-master/.wigwam/build.generated.sh]
Running installation script now:

cython:
      Fetching...  ok [elapsed 0m1s]
   Configuring...  ok [elapsed 0m1s]
     Compiling...  skipped
    Installing...  error!

Error occurred while installing [cython]. Press <ENTER> to open [/home/machine/Downloads/mpegflow-master/.wigwam/log/cython/install.txt], press <ESC> to quit.

BEGIN_ENV
PATH=/home/machine/Downloads/mpegflow-master/.wigwam/prefix/bin:/home/machine/Downlo
ads/mpegflow-master/.wigwam/prefix/deb/usr/bin:/home/machine/Downloads/mpegflow-ma
ster/.wigwam/prefix/python/bin:/home/machine/bin:/home/machine/.local/bin:/usr/local
/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/
snap/bin
LD_LIBRARY_PATH=/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64:/home
/machine/Downloads/mpegflow-master/.wigwam/prefix/lib:/home/machine/Downloads/mpegfl
ow-master/.wigwam/prefix/deb/usr/lib:/home/machine/Downloads/mpegflow-master/.wigw
am/prefix/deb/usr/lib/x86_64-linux-gnu:
CPATH=/home/machine/Downloads/mpegflow-master/.wigwam/prefix/include:/home/machine/D
ownloads/mpegflow-master/.wigwam/prefix/deb/usr/include:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/python/include/python2.7:
LIBRARY_PATH=/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu:

g++ -print-search-dirs:
install: /usr/lib/gcc/x86_64-linux-gnu/5/
programs: =/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/bin/
libraries: =/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64/x86_64-linux-gnu/5/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64/x86_64-linux-gnu/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64/../lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib/x86_64-linux-gnu/5/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib/x86_64-linux-gnu/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib/../lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/5/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/../lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/5/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/../lib/:./x86_64-linux-gnu/5/:./x86_64-linux-gnu/:./../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/5/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/5/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib64/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/:/home/machine/Downloads/mpegflow-master/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:./:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/

PWD=/home/machine/Downloads/mpegflow-master/.wigwam/src/cython
END_ENV

Unable to find pgen, not compiling formal grammar.
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/home/machine/Downloads/mpegflow-master/.wigwam/prefix/python/lib/python2.7/site-packages/test-easy-install-20814.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/machine/Downloads/mpegflow-master/.wigwam/prefix/python/lib/python2.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by vadimkantorov** [comment]
I fixed a bug, you may try to run `wigwam clean --wigwamfile --dangerous` and then start over again

**Comment by DBraun** [comment]
Thanks that fixed it!
