### ISSUE TITLE
error when installing hdf5

### ISSUE THREAD

**Issue by truetqy** [vadimkantorov/wigwam#6]
Hi,
I am using wigwam to install these packages:
wigwam install torch hdf5 matio protobuf octave -DPATH_TO_NVCC="/usr/local/cuda/bin/nvcc" -DPATH_TO_CUDNN_SO="/usr/local/cuda/lib64/libcudnn.so"

But there is an error when installing hdf5:

hdf5:
      Fetching...  error!

Error occurred while installing [hdf5]. Press <ENTER> to open [/home/qt/.wigwam/log/hdf5/fetch.txt], press <ESC> to quit.

In the log file: 

--2017-07-25 07:52:10--  http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz
Resolving www.hdfgroup.org (www.hdfgroup.org)... 23.185.0.1, 2620:12a:8001::1, 2620:12a:8000::1
Connecting to www.hdfgroup.org (www.hdfgroup.org)|23.185.0.1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz [following]
--2017-07-25 07:52:10--  https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz
Connecting to www.hdfgroup.org (www.hdfgroup.org)|23.185.0.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz [following]
--2017-07-25 07:52:10--  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz
Resolving support.hdfgroup.org (support.hdfgroup.org)... 50.28.50.143
Connecting to support.hdfgroup.org (support.hdfgroup.org)|50.28.50.143|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-07-25 07:52:11 ERROR 404: Not Found.

I have checked the downloading url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz
It is no longer there. I think the file is moved to https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz

Please advice how should I change the path/ can help to update the url in your repo? 
Or is there any other problems causing the error?

**Comment by vadimkantorov** [comment]
Thanks for reporting. I updated the URL, it should hopefully work now.
