### ISSUE TITLE
Problem with bzip download

### ISSUE THREAD

**Issue by david-kohen** [vadimkantorov/wigwam#7]
Hi - great idea, but as installed it's dying on the bzip file - the link is dead and returns an html instead of the tar. As far as I can see the website is abandoned - the git is still up and 1.0.6 is included at least in the Debian-based repositories. 

Thought you's like to know

**Comment by vadimkantorov** [comment]
Hi! Unfortunately I don’t support wigwam actively anymore, since conda mostly fulfills it’s goals.

Good luck!
